import SpLean.Hypergraph.Semantics
import Mathlib.Logic.Relation

/-!
# Isomorphism, and that it preserves the denotation

The point of the hypergraph: two diagrams with isomorphic hypergraphs denote
the same tensor, so equivalence can be settled by exhibiting a bijection rather
than by a derivation.

## Up to the identifications

`compose` records merged wires in `ids` rather than renumbering, so a `Hyp` is
not a normal form and a plain bijection on wires is *not* the right notion. It
is not merely inconvenient, it is too weak to be useful: in `toHyp Gate.CNOT`
the Z spider's input leg is literally the boundary input wire, while in
`toHyp Gate.CNOT'` the boundary input is a separate wire *identified* with the
spider's leg. No bijection matches those, and the two are certainly the same
diagram.

So everything below is stated up to `Hyp.Rel`, the equivalence generated by the
recorded pairs, and the two wire maps are inverse only up to it. That also lets
an isomorphism relate hypergraphs with different wire counts, which is needed
as soon as one side has been composed with a bare `wire`.

## Fixing the boundary

`map_inputs` and `map_outputs` pin the boundary *pointwise and in order*. This
is the one condition that cannot be relaxed: an isomorphism free to permute
boundary ports would identify a crossing with two parallel wires and prove
`swap ≈zx wire ⊗ wire`. See `sem_swap_ne_sem_parallel` at the end of the file,
which is the standing test that this has not been dropped.
-/

namespace SpLean.Hypergraph

variable {Φ : Type} {n m : ℕ}

/-- The equivalence on wires generated by the recorded identifications. -/
def Hyp.Rel (H : Hyp Φ n m) : Fin H.wires → Fin H.wires → Prop :=
  Relation.EqvGen fun u v => ∃ k, H.ids k = (u, v)

/-! `Hyp.Rel` is a `def` wrapping `Relation.EqvGen`, so dot notation on a
hypothesis cannot see the constructors through it. These three restate them. -/

@[refl] theorem Hyp.Rel.refl {H : Hyp Φ n m} (u : Fin H.wires) : H.Rel u u :=
  Relation.EqvGen.refl _

theorem Hyp.Rel.symm {H : Hyp Φ n m} {u v : Fin H.wires} (h : H.Rel u v) : H.Rel v u :=
  Relation.EqvGen.symm _ _ h

theorem Hyp.Rel.trans {H : Hyp Φ n m} {u v w : Fin H.wires} (h₁ : H.Rel u v) (h₂ : H.Rel v w) :
    H.Rel u w :=
  Relation.EqvGen.trans _ _ _ h₁ h₂

/-- A wire pair as recorded is related. -/
theorem Hyp.rel_ids (H : Hyp Φ n m) (k : Fin H.idCount) : H.Rel (H.ids k).1 (H.ids k).2 :=
  Relation.EqvGen.rel _ _ ⟨k, rfl⟩

/-- An assignment that respects the recorded pairs respects everything they
generate. This is why `Hyp.sem` can afford to state only the generators. -/
theorem Hyp.Sat.rel {H : Hyp Φ n m} {a : Fin H.wires → Bool} (ha : H.Sat a)
    {u v : Fin H.wires} (h : H.Rel u v) : a u = a v := by
  induction h with
  | rel x y hxy => obtain ⟨k, hk⟩ := hxy; have := ha k; rw [hk] at this; exact this
  | refl x => rfl
  | symm x y _ ih => exact ih.symm
  | trans x y z _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- An isomorphism of hypergraphs: a matching of wires and of boxes that fixes
the boundary, all of it up to `Hyp.Rel`.

`wire` and `wireInv` are inverse only up to the identifications, and the box
matching pairs each box with one of the same label whose legs correspond under
some reindexing — a spider does not care what order its legs come in. -/
structure Iso (H₁ H₂ : Hyp Φ n m) where
  /-- Where each wire of `H₁` goes. -/
  wire : Fin H₁.wires → Fin H₂.wires
  /-- And back. -/
  wireInv : Fin H₂.wires → Fin H₁.wires
  left_inv : ∀ v, H₁.Rel (wireInv (wire v)) v
  right_inv : ∀ v, H₂.Rel (wire (wireInv v)) v
  map_rel : ∀ u v, H₁.Rel u v → H₂.Rel (wire u) (wire v)
  map_rel_inv : ∀ u v, H₂.Rel u v → H₁.Rel (wireInv u) (wireInv v)
  /-- The boundary is fixed pointwise and in order. -/
  map_inputs : ∀ i, H₂.Rel (wire (H₁.inputs i)) (H₂.inputs i)
  map_outputs : ∀ j, H₂.Rel (wire (H₁.outputs j)) (H₂.outputs j)
  /-- Which box of `H₂` each box of `H₁` becomes. -/
  boxPerm : Fin H₁.boxCount ≃ Fin H₂.boxCount
  map_label : ∀ i, (H₁.boxes i).label = (H₂.boxes (boxPerm i)).label
  /-- Legs correspond in some order. -/
  legPerm : ∀ i, Fin (H₁.boxes i).arity ≃ Fin (H₂.boxes (boxPerm i)).arity
  map_legs : ∀ i k,
    H₂.Rel (wire ((H₁.boxes i).legs k)) ((H₂.boxes (boxPerm i)).legs (legPerm i k))

namespace Iso

variable {H₁ H₂ : Hyp Φ n m}

/-- The wire matching, read on assignments: pulling back along `wireInv` takes
the assignments `H₁.sem` sums over to the ones `H₂.sem` does, bijectively. This
is the whole content of `sem_eq` — the rest is checking the summands agree. -/
def assignEquiv (I : Iso H₁ H₂) :
    {a : Fin H₁.wires → Bool // H₁.Sat a} ≃ {b : Fin H₂.wires → Bool // H₂.Sat b} where
  toFun a := ⟨a.1 ∘ I.wireInv, fun k =>
    a.2.rel (I.map_rel_inv _ _ (H₂.rel_ids k))⟩
  invFun b := ⟨b.1 ∘ I.wire, fun k =>
    b.2.rel (I.map_rel _ _ (H₁.rel_ids k))⟩
  left_inv a := Subtype.ext (funext fun v => a.2.rel (I.left_inv v))
  right_inv b := Subtype.ext (funext fun v => b.2.rel (I.right_inv v))

/-- A wire and its image carry the same bit, for any assignment respecting the
identifications. -/
theorem apply_eq (I : Iso H₁ H₂) {a : Fin H₁.wires → Bool} (ha : H₁.Sat a)
    {u : Fin H₁.wires} {v : Fin H₂.wires} (h : H₂.Rel (I.wire u) v) :
    a u = (a ∘ I.wireInv) v :=
  (ha.rel (I.left_inv u)).symm.trans (ha.rel (I.map_rel_inv _ _ h))

end Iso

/-- **Isomorphic hypergraphs denote the same tensor.**

The sum is transported along `assignEquiv`; the boundary indicators agree
because the boundary is fixed, and the box products agree box by box because
`Label.tensor` does not care what order a box's legs come in. -/
theorem Iso.sem_eq (expI : Φ → ℂ) {H₁ H₂ : Hyp Φ n m} (I : Iso H₁ H₂)
    (f : Bits n) (g : Bits m) : H₁.sem expI f g = H₂.sem expI f g := by
  rw [H₁.sem_eq_sum_sat expI f g, H₂.sem_eq_sum_sat expI f g]
  refine Fintype.sum_equiv I.assignEquiv _ _ fun a => ?_
  have hin : ∀ i, a.1 (H₁.inputs i) = (I.assignEquiv a).1 (H₂.inputs i) :=
    fun i => I.apply_eq a.2 (I.map_inputs i)
  have hout : ∀ j, a.1 (H₁.outputs j) = (I.assignEquiv a).1 (H₂.outputs j) :=
    fun j => I.apply_eq a.2 (I.map_outputs j)
  simp only [hin, hout]
  congr 1
  refine Fintype.prod_equiv I.boxPerm _ _ fun i => ?_
  rw [I.map_label i]
  exact Label.tensor_congr expI _ (I.legPerm i) fun k => I.apply_eq a.2 (I.map_legs i k)

/-! ## The standing test

`Iso` fixes the boundary pointwise. Drop that and a crossing becomes
isomorphic to two parallel wires — same wires, same (no) boxes, same (no)
identifications, differing only in which output port each wire is. These two
hypergraphs are written by hand rather than lowered from terms, since this
module imports neither representation; `swapHyp` is what `ZX.swap` lowers to.

`sem_swap_ne_sem_parallel` is what makes it a test with teeth: the two
denotations genuinely differ, so by `Iso.sem_eq` no isomorphism between them
can exist. If a future weakening of `Iso` ever admits one, this file stops
compiling. -/

/-- Two parallel wires. -/
def parallelHyp : Hyp Φ 2 2 where
  wires := 2
  boxCount := 0
  boxes := Fin.elim0
  idCount := 0
  ids := Fin.elim0
  inputs := id
  outputs := id

/-- A crossing: the same data, with the outputs swapped. -/
def swapHyp : Hyp Φ 2 2 where
  wires := 2
  boxCount := 0
  boxes := Fin.elim0
  idCount := 0
  ids := Fin.elim0
  inputs := id
  outputs := ![1, 0]

theorem sem_swap (expI : Φ → ℂ) :
    (swapHyp : Hyp Φ 2 2).sem expI ![false, true] ![false, true] = 0 := by
  refine Finset.sum_eq_zero fun a _ => ?_
  by_cases h : (∀ i, a ((swapHyp : Hyp Φ 2 2).inputs i) = (![false, true] : Bits 2) i) ∧
      (∀ j, a ((swapHyp : Hyp Φ 2 2).outputs j) = (![false, true] : Bits 2) j)
  · exfalso
    have h0 := h.1 1
    have h1 := h.2 0
    simp only [swapHyp, id_eq, Matrix.cons_val_one, Matrix.cons_val_zero, Matrix.head_cons] at h0 h1
    rw [h0] at h1
    exact absurd h1 (by decide)
  · rw [if_neg h]
    ring

theorem sem_parallel (expI : Φ → ℂ) :
    (parallelHyp : Hyp Φ 2 2).sem expI ![false, true] ![false, true] = 1 := by
  rw [Hyp.sem]
  simp only [parallelHyp]
  rw [Finset.sum_eq_single ![false, true]]
  · simp [Hyp.Sat]
  · intro b _ hb
    have hcond : ¬ ((∀ i, b (id i) = (![false, true] : Bits 2) i) ∧
        (∀ j, b (id j) = (![false, true] : Bits 2) j)) := by
      rintro ⟨h₁, -⟩
      exact hb (funext fun i => h₁ i)
    rw [if_neg hcond]
    ring
  · simp

/-- The crossing and the parallel wires denote different tensors, so no `Iso`
relates them — the boundary condition in `Iso` is load-bearing. -/
theorem sem_swap_ne_sem_parallel (expI : Φ → ℂ) :
    (swapHyp : Hyp Φ 2 2).sem expI ![false, true] ![false, true]
      ≠ (parallelHyp : Hyp Φ 2 2).sem expI ![false, true] ![false, true] := by
  rw [sem_swap, sem_parallel]
  exact zero_ne_one

theorem not_nonempty_iso_swap_parallel (expI : Φ → ℂ) :
    ¬ Nonempty (Iso (swapHyp : Hyp Φ 2 2) parallelHyp) := by
  rintro ⟨I⟩
  exact sem_swap_ne_sem_parallel expI (I.sem_eq expI _ _)

end SpLean.Hypergraph
