import LeanSpider.Algebraic.Phase
import LeanSpider.Algebraic.ZX
import LeanSpider.Algebraic.Semantics
import LeanSpider.Algebraic.Congruence
import LeanSpider.Algebraic.SpiderFusion
import LeanSpider.Algebraic.Rewrite
import LeanSpider.Algebraic.Tactics
import LeanSpider.Algebraic.Visualize
import LeanSpider.Algebraic.Gates
